name: Commitlint
permissions:
  contents: read

on:
  pull_request:
    branches: [ main, rc ]
  push:
    branches: [ main, rc ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Validate current commit (last commit)
        if: github.event_name == 'push'
        run: |
          git log -1 --pretty=format:"%s" > /tmp/commit_msg
          pre-commit run conventional-pre-commit --hook-stage commit-msg --commit-msg-filename /tmp/commit_msg

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: |
          # Get all commit messages in the PR
          git log --pretty=format:"%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > /tmp/pr_commits
          # Validate each commit message
          while IFS= read -r commit_msg; do
            echo "$commit_msg" > /tmp/commit_msg
            pre-commit run conventional-pre-commit --hook-stage commit-msg --commit-msg-filename /tmp/commit_msg
          done < /tmp/pr_commits
